### ISSUE TITLE
Arduino example doesn't work

### ISSUE THREAD

**Issue by JT-PO** [neonode-inc/zforce-arduino#11]
Hello, I try to use the zForce AIR 209 and I followed all the steps given to use it. I connect the I2C of the sensor to the Arduino UNO and I use the +5v of the Arduino UNO to power the sensor. I launched the example given here it stop after the reception of ReverseY as you cans see it in the attached picture.
![IMG_2085](https://user-images.githubusercontent.com/53530115/62222769-310e0b80-b3b4-11e9-8bd7-6cd591f255f6.jpg)

**Comment by JT-PO** [comment]
Here is the wiring that I did.
![image1](https://user-images.githubusercontent.com/53530115/62223089-a8439f80-b3b4-11e9-8a0d-c5e8c49fbfad.jpeg)

**Comment by olinanton** [comment]
Hi,

Great to see you trying out the library. From the picture it looks like you have connected pin 13 to 3.3v which would assert data ready (DR) to constantly be high. The DR pin should be asserted by the sensor. Try connecting pin 13 on the board to DR on the interface board and it will most likely work.

Best regards,
Anton

**Comment by JT-PO** [comment]
Great! It works. Thank you very much for your help, I was struggling with this problem.

Best regards,
Jorge TAPIA.

**Comment by intellimation** [comment]
> Great! It works. Thank you very much for your help, I was struggling with this problem.
> 
> Best regards,
> Jorge TAPIA.

Hi, I am trying something similar. Is it possible to share the code that you are using for reading from the sensor. I want to track the position which is being touched and take actions accordingly. Pls help !
