### ISSUE TITLE
Connecting to a Arduino board - 

### ISSUE THREAD

**Issue by intellimation** [neonode-inc/zforce-arduino#25]
I have bought a ZForce Air 2 Device with the interface board. I want to connect the Arduino board ( purchased from the market ). I am new to the Arduino programming. Can you pl. let me know how to integrate this with Aurdino board. If there is an example code with connection schematic diagram, it will be of great help.

**Comment by olinanton** [comment]
Hi,

This is all available on the Neonode support site. I recommend you to take a look at the documentation available: https://support.neonode.com/docs/display/NPB/User%27s+Guide+-+Neonode+Prototyping+Board

If the documentation is not sufficient to get you started, please contact the support team at https://helpcenter.neonode.com/hc/en-us/requests/new 

// Anton
