### ISSUE TITLE
Double 0xEE in zForce request messages unclear

### ISSUE THREAD

**Issue by emielsteerneman** [neonode-inc/zforce-arduino#52]
For our student team RoboTeam Twente, in which we build soccer robots, we use the zForce Air to detect if a ball is in front of a robot. I've been looking through our code and I noticed something strange, which I noticed in the [Arduino code](https://github.com/neonode-inc/zforce-arduino/blob/f28d7e04c85208e39f6be6f609dc81cb9b99739e/src/Zforce.cpp#L161) ​as well.

Request messages that are send to the zForce Air always start with two 0xEE bytes. For example, the [`GetEnable` command](https://github.com/neonode-inc/zforce-arduino/blob/f28d7e04c85208e39f6be6f609dc81cb9b99739e/src/Zforce.cpp#L141) : `0xEE, 0x08, 0xEE, 0x06, 0x40, 0x02, 0x02, 0x00, 0x65, 0x00`. First, 0xEE with 8 bytes, and directly after that 0xEE with 6 bytes.

I've been searching through the [documentation](https://support.neonode.com/docs/download/attachments/2490665/Neonode%20Touch%20Sensor%20Module%20User%27s%20Guide.pdf) and the [.asn file](https://support.neonode.com/docs/download/attachments/1671913/zforce_pdu_def.asn?version=5&modificationDate=1617196895908&api=v2) to find a reason for the double 0xEE byte, but I've come up empty. The .asn file tells me that the 0xEE byte indicates a top-level `request [PRIVATE 14]` message. It seems strange to me to send a top-level message twice. Is this second 0xEE byte actually needed, or is it redundant?

**Comment by olinanton** [comment]
Hi, the first two bytes are the I2C header bytes, and everything following that is the ASN.1 serialized message.
