### ISSUE TITLE
zForce with RPi3

### ISSUE THREAD

**Issue by karishmabava** [neonode-inc/zforce-arduino#7]
Hi,

I just bought a zforce sensor and wanted it to run with Rpi 3. Do you have any documentation/ Code Examples for that?

Thank you,
Karishma

**Comment by antonneonode** [comment]
Hi,

For Raspberry Pi or other systems running linux we have an SDK (only USB and not I2C) called the zForce SDK. It is available here: https://support.neonode.com/docs/display/Downloads/zForce+SDK+Downloads and documentation is available on the same webpage. For future questions regarding the zForce AIR Sensor please create a request at helpcenter.neonode.com instead.

Best regards,
Anton Olin
Support Engineer
